### ISSUE TITLE
Undo is broken and corrupts blocks

### ISSUE THREAD

**Issue by pmbauer** [Roam-Research/issues#114]
**Describe the bug**

Undo is broken and corrupts blocks

[video link](https://www.dropbox.com/s/yrqmpp202irzx1w/Screen%20Recording%202020-05-06%20at%206.09.57%20PM.mov?dl=0)

**To Reproduce**
1. Start with a list of blocks (try more than 3), each containing ✅❌
1. Go down the list and delete a ✅ or an ❌ from each block
1. Type `CMD-z` to undo the edits
1. The edits are not undone, blocks are corrupted to non-existing previous states.
1. Type `CMD-SHIFT-z`
1. The undo actions are not reverted

**System Information:**
 - Roam version: 0.5.0-43911ff0
 - Device: desktop
 - OS: MacOS 10.15.4
 - Browser: Brave

**Additional Context**
I have a green dot

**Comment by ChenMorSays** [comment]
Also experiencing this issue!

**Comment by vitalwarley** [comment]
I had a problem with undo / redo a few minutes ago when trying to reorder some blocks. Sadly, some data _was_ lost. A block that was lost is linked as a mention but it can't be shown anymore. 

![Peek 16-07-2020 20-24](https://user-images.githubusercontent.com/6365065/87732320-08d51380-c7a3-11ea-8ef1-4f8f39ec3364.gif)

Also, some blocks turn out to be non-editable or deletable. When I click on them they don't show a reference in the address bar.

**Comment by Sigfried** [comment]
When I brought up [this problem on the forum](https://forum.roamresearch.com/t/the-single-biggest-problem-with-roam-undo-redo/754) @pmbauer pointed me to this issue. So I'm chiming in here with the description of the problem as I've experienced it.

> I’ve been using Roam for many hours a day for many months and I’ve encountered a variety of frustrations (along with all the things a like, which are what got me to subscribe as a believer), and by far the worst and most costly is the weirdness of the undo feature.
> 
> I make a lot of mistakes in everything I do. In Vim I constantly use the many-level undo. Even though my coding and writing process both rely on very frequent git commits, I occasionally find myself going dozens of steps back in Vim’s undo cache (dozens? I just hold my finger on the u and wait a long time, so who knows.) These can be delicate operations, so (besides backing up) I try to be super careful to just find and copy whatever I lost and not make any changes that could screw up my ability to redo all the stuff I just indid.
> 
> Roam’s undo/redo cache is just baffling. I believe it’s database- not page-centric. So you if you made a change on another page three actions ago, ctrl/cmd-z will undo the last two as you expect, and then jump to the other page to start undoing stuff there. I understand that the whole graph is intimately interconnected, so it might be impossible to do it any other way, but it’s a usability nightmare: I just undid my last two changes, having accidentally overwritten some important text a bunch of changes ago, and I’m expecting to be able to redo them after I find what I lost; but then I suddenly jump to another page.
> 
> If Roam’s undo/redo worked as reliably as Vim’s, this would be tolerable, but it doesn’t. After some unknown (and varying?) number of undo steps (on one page or multiple), undo stops working. But you can’t tell exactly when that is or will be, because some undo steps happen off-screen if you’ve got a long page.
> 
> But at some point also, redo stops working as well!

**Comment by filipesilva** [comment]
Heya, we just merged a fix that cleans up the undo logic and should fix this. It should be rolling out during the day to all users.

**Comment by ChenMorSays** [comment]
@filipesilva thanks! looking forward.

**Comment by KerickHowlett** [comment]
This big is still present—or at least a variety of it—I'm constantly having issues with simple undos and redos.
