### ISSUE TITLE
Notes are not being saved

### ISSUE THREAD

**Issue by s-tikhomirov** [Roam-Research/issues#616]
**Describe the bug**

My notes are simply not being saved.

**To Reproduce**

1. Open Roam, see an empty Daily notes page
2. Type something
3. Wait for the green dot in the upper right corner to become green
4. Reload the page (press F5)
5. See an empty Daily notes page

**System Information:**
 - Roam version: [0.7.5-19b6cf36]
 - Device: [Laptop]
 - OS: [Ubuntu 18.04.5 LTS]
 - Browser [Chrome 86.0.4240.111, Firefox 82.0.3]

**Additional context**

This issue is quite a disappointment for me as a new user of Roam. Have been hearing great things about the tool, decided to try it out only do discover it does not do the one most basic things a notes tool is supposed to do - save notes.

I have tried switching off all browser plugins including an adblocker and allowing third-party cookies -- it didn't help.

**Comment by ryanduncan** [comment]
I signed up for ROAM yesterday and am having the exact same issue.  MacOS / Big Sur and have reproduced the issue across Safari, Firefox and Chrome.  Nothing is being saved.  A brand new instance of ROAM opens on every page refresh.

**Comment by JonathanLorand** [comment]
i'm also having issues with saving (i'm not a new user). and i then signed out to try to sign back in afresh, but can't seem to login anymore.

**Comment by Bardia95** [comment]
Please update Roam and refresh should be fixed!

**Comment by JonathanLorand** [comment]
roam is still not loading for me (have tried on multiple devices). i'm not sure how to update roam if i can't sign in - is that possible?
